---
title: "January 18 meeting"
output: html_document
---

# What are statistical models
Statistical models describe uncertainty - that's what makes them different from calculations/equations.

# Why do we use them?
fundamentally:  

- to make decisions from uncertainty  

practically:  

- predicting what can happen in the future  
- state of things in the past
- describe a process/relationship
- are you modelling for job of getting predictive function or do you want to understand the system?  

Scientific statistical models - our parameters mean something - we want to understand process (as opposed to extreme versions of machine learning models that are purely predictive)

# How do they work?
Fundamental concept in statistical model is maximum likelihood.
If this model is true - what is probability that it would produce these data.
Let's say you have a model with set number of parameters. Each parameter coudl take a set of possible continuous values. Maximum likelihood is process of determining parameter values that are most likely to have given rise to the data.

Bayesian models are essentiallly ML (likelihood-based) but with prior information. Multiply posteriors by priors.  With Bayesian it is possible that you dont think the most likely model is true because yo already know something about the system. 
